# Generated by Django 5.1.5 on 2025-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, null=True, to='books.genre', verbose_name='Preferred Genres'),
        ),
    ]
