# Generated by Django 5.1.5 on 2025-01-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_publish_data_book_publish_date_and_more'),
        ('users', '0002_user_preferred_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, to='books.genre', verbose_name='Preferred Genres'),
        ),
    ]
