# Generated by Django 5.1.5 on 2025-02-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='viewed',
        ),
    ]
