# Generated by Django 5.1.5 on 2025-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
